project:
  type: website
  render: 
    - "index.qmd"
    - "!duckdb/"
    - "layouts/"
    - "reactives/"
    - "modules/"
  output-dir: docs
  post-render:
    - "cp -rnv reactives/reactivity.pdf docs/"

website:
  title: "shinyowl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: layouts/index.qmd
        text: Layouts
      - href: reactives/index.qmd
        text: Reactivity
      - href: modules/index.qmd
        text: Modules

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

