project:
  type: website

website:
  title: "shinyowl"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - reactives/reactive_programming.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

